### ISSUE TITLE
Create a standardized issues template

### ISSUE THREAD

**Issue by gallorob** [GoodAI/space-engineers-ai-spaceship-generator#1]
The template should include what the issue is, the severity, and a short description of what happened.

Users should also be invited to update the relevant log file (`log_{TIMESTAMP}.log`) for inspection. The log file does not contain any user information **if** they declined the privacy policy or have already completed the user study.

**Comment by martinpoliak-goodai** [comment]
I added a unified issue template for bugs and feature requests, thanks for the suggestion!
