### ISSUE TITLE
Controle Slider(s) for ship Size to generate

### ISSUE THREAD

**Issue by twotwinbrothers** [GoodAI/space-engineers-ai-spaceship-generator#12]
*Issue type:*  [ feature request ]

*Severity:*  [medium ]

**Describe the issue**
Is it possilbe to make a slider(s) so you can decide the increase or decrease the size before you generate ships,  

Now it makes really Big ships, that takes a lot of time te generate and arend really ussable in SE.  The Smaller ship are already the size of Xoc Xebon Battlecruiser, Too Large!

**Comment by gallorob** [comment]
Hi @twotwinbrothers, I believe this can be implemented without too many difficulties. However, keep in mind that this will reduce the amount of new spaceships that can be generated per iteration. Also, I believe different tilesets would also play a role in the sizes of spaceships generated.

Nonetheless, I believe I can work on this once the user study is over, as such a feature would alter the end results.

In the meantime, do you think entering a maximum size (i.e.: three integer values for the X, Y, and Z dimensions) arbitrarily would be better than a slider? What do you think the range of the slider should be?

**Comment by twotwinbrothers** [comment]
I think from 100m to1500m ish (1000m is huge (400 blocks), i don't know how big de limiti s?

Form field is oke for Max size for X,Y,Z. to

**Comment by gallorob** [comment]
Hi @twotwinbrothers, sorry this feature implementation took so long! I've implemented the filter for different dimensions, which are specified in the config file upon launch. Here's how it looks:
![immagine](https://user-images.githubusercontent.com/32876132/210837899-1c0a7a83-5f32-42ab-b8b1-c9443e02bc11.png)
A red outline on the input area means that you've entered a number that is larger than the largest allowed value for that dimension (again, defined in the config file).

Changes should be out in the next release, so I'm closing the issue.
