### ISSUE TITLE
Minor Spelling Error in App Info

### ISSUE THREAD

**Issue by WarpZephyr** [GoodAI/space-engineers-ai-spaceship-generator#13]
*Issue type: Bug* 
*Severity: Low*

**Describe the issue**
Minor spelling error I noticed, shown in the screenshot and underlined,
"spacehsip"

**To Reproduce**
1. Load up webpage with program
2. Click on "App Info"
3. See spelling error in screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/107563368/203884841-86d95c02-2aa3-4d3d-9016-10aa85017df1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - .exe file name: Spaceship.Generator.v1.0.3.exe

**Comment by gallorob** [comment]
@WarpZephyr thank you pointing it out! Fixed in 26a938a608514e669cffb343fff06d2752da0524, will be updated with the next release.
