### ISSUE TITLE
More thruster variations

### ISSUE THREAD

**Issue by Droid-B1045** [GoodAI/space-engineers-ai-spaceship-generator#16]
*Issue type:* [ feature request ]

**My idea:**
Add more thruster templates to the ai to choose from i understand the generating the large thrusters might be problematic since even the small ones get placed in the wrong place sometimes: ![image](https://user-images.githubusercontent.com/119160801/204130090-a9d336f0-355f-4841-abe7-57e52034a518.png)

but you could add a thruster bay that has a different formation, maybe one with more or fewer thrusters
for example:
![image](https://user-images.githubusercontent.com/119160801/204130108-3f74be58-0c43-41d6-915e-1b62ae77e763.png)
![image](https://user-images.githubusercontent.com/119160801/204130159-ef322bdf-8108-4fcd-b3dd-6854838a2994.png)

this could be done with different shaped cockpits and reactor rooms.

**Comment by gallorob** [comment]
Hi @Droid-B1045, I like the idea of more, different thruster tiles! Currently there is only one variation of thrusters, and is embedded in the executable (if you run from source, this is defined in the [`user-study/llrules`](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/blob/main/user-study/llrules) file).

Adding a new variation is pretty simple, and I do intend to publish a short guide on how to add custom tiles in the application once it's out of the user study period.

I'll keep this suggestion open for now, and close it once the aforementioned guide is out!

**Comment by gallorob** [comment]
Hi @Droid-B1045, I've created an executable which will be bundled in the next release that helps in adding new tiles easily.

I'm going to write the ![wiki](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/wiki) article shortly, so I'm closing the issue for now.
