### ISSUE TITLE
Comparator Crash

### ISSUE THREAD

**Issue by Zemogiter** [GoodAI/space-engineers-ai-spaceship-generator#2]
*Issue type:* bug 

*Severity:* high (application-breaking) 

**Describe the issue**
When I launch `Spaceships.Comparator.v1.0.0.exe` after a while it crashes with the following message in the cmd window:
```
Traceback (most recent call last):
File "comparator_webapp_launcher.py", line 12, in <module>
File "<frozen importlib_bootstrap>", line 1027, in _find_and_load
File "<frozen importlib_bootstrap>", line 1066, in _find_and_load_unlocked
File "<frozen importlib_bootstrap>", line 688, in _load_unlocked
File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
File "pcgsepy\guis\ships_comparator\webapp.py", line 66, in <module>
File "pcgsepy\setup_utils.py". line 83, in get_default_lsystem
File "pcgsepy\lsystem\rules.py", line 94, in _init_
FileNotFoundError: [Errno 2] No such file or directory: "hlrules_sm"
[13420] Failed to execute script "comparator_webapp_launcher" due to unhandled exception!
```

**To Reproduce**
1. Launch the aforementioned exe file 
2. See error after about 10 seconds.

**Expected behavior**
Comparator UI showing up.

**Screenshots**

![Zrzut ekranu (286)](https://user-images.githubusercontent.com/24385408/198393356-e99175ba-42c7-4e2a-879e-0e3261041493.png)

**Log file**
I found no log file in the directory the exe file was.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser: Chrome 106.0.5249.119
 - .exe file name: Spaceships.Comparator.v1.0.0.exe

**Additional context**
Tried laucnhing the comparator exe with admin rights, same results. Also tried runing comparator while the main app is running vs when it's not.

**Comment by hobob0t** [comment]
Same issue here. Running from source code seems to work, though.

**Comment by rootli** [comment]
Same here. Does it work only with a results file from the completed ux study, perhaps? 

A comment: The survey is not very respectful of participants' time. The app is so slow (at least for me) that completing 5(?) more rounds would take me all night. I wait so long after each click that I forget which box I have clicked before or which box I wanted to click next. XD

**Comment by gallorob** [comment]
The bulding script for the comparator app wasn't update, my fault, sorry! If you've already completed the rest of the user study, please run the comparator app from source until the next release of the executable.

This issue will be fixed with the next release.

As for the time, that's a totally fair statement: we are aware the application can get pretty resource-intensive, so if you're unable to participate because of that, it's understandable! Hopefully the application can be refined and improved so that you can still play around with it in user mode :)

**Comment by gallorob** [comment]
@martinpoliak-goodai please merge commit https://github.com/arayabrain/space-engineers-ai-spaceship-generator/commit/25d0300c22a5075e89f0564e1deb2cf56fd4ae0c in the repo and build the new Spaceships Comparator app, thank you!

@Zemogiter @hobob0t @rootli thank you for reporting this issue, it's now fixed (as mentioned above, you can still run from the source code with no issues, or wait for the new release of the app).

**Comment by rootli** [comment]
Thanks! My main feedback would be, it's already doing a great job creating shapes that inspire me to turn a generic hull into a purpose-bound ship! I'd be interested in settings for more/less symmetry, min/max length, atmo/ion toggle.

**Comment by Pontiac76** [comment]
I tried to run the compare scripts from the CLI under Win10 and have nothing but errors.  I'll leave the browser open until the EXE gets updated.  I'll keep an eye on it.

**Comment by gallorob** [comment]
@Zemogiter @hobob0t @rootli @Pontiac76 I added the new comparator executable release, available at https://github.com/GoodAI/space-engineers-ai-spaceship-generator/releases/tag/v.1.0.1

Thank you for your patience, this will allow you to complete the user study now 😃
