### ISSUE TITLE
Update documentation now that user study is over

### ISSUE THREAD

**Issue by martinpoliak-goodai** [GoodAI/space-engineers-ai-spaceship-generator#20]
Hi Roberto, 
could you please update readme.md now that user study is over? The user study mode / spaceship ranker references are now obsolete.

**Comment by gallorob** [comment]
Update readme and documentation in fcb8727dc2edc549034bca23fb9af3ef20c42c88

**Comment by martinpoliak-goodai** [comment]
Thanks Roberto. I noticed the readme does not show how to enter "developer mode" - is it OK for you to include this information there?

________________________________

**Comment by gallorob** [comment]
Good point, I've updated the readme
