### ISSUE TITLE
Publish latest release

### ISSUE THREAD

**Issue by gallorob** [GoodAI/space-engineers-ai-spaceship-generator#21]
@martinpoliak-goodai I could not open a new branch to push the latest changes for a PR, so they're currently on main.

The new version introduces:
- a size filter, as suggested in https://github.com/GoodAI/space-engineers-ai-spaceship-generator/issues/12
- exclude configuration and tiles/atoms files, so that users can:
  - control all properties of the application (solves https://github.com/GoodAI/space-engineers-ai-spaceship-generator/issues/14)
  - create their own tilesets from a Space Engineers blueprint (feature requested https://github.com/GoodAI/space-engineers-ai-spaceship-generator/issues/16)

As for the last point, the application also now builds a "TilesMaker.exe", which is a simple command line program to easily generate the tiles rules and properties.

Please try compile the application and try running it. Make sure the following files are in the same directory as the executable:
- block_definitions.json
- common_atoms.json
- configs.ini
- hl_atoms.json
- hlrules
- hlrules_sm
- llrules
As such, these will also be needed by the users, so I would suggest releasing the application as a .zip file for conveniency sake.

As I mentioned previously, I won't be able to support this repository anymore, but if there are issues with this release I should be able to work on them 😃

**Comment by martinpoliak-goodai** [comment]
Thanks Roberto. Could you please update the Readme to reflect the latest update, especially how to use (and for what) the TilesMaker app? Meanwhile I'm building the app to test if things work fine.

**Comment by martinpoliak-goodai** [comment]
TilesMaker fails to find a "tileset" file - can you please push it?

**Comment by gallorob** [comment]
Updating the README.

As for the tileset, it's a folder. I'm going to update the script so that it creates it if not found.

**Comment by martinpoliak-goodai** [comment]
Hmm, the built executable is not able to locate the "common_atoms.json" file, even if it is located in the same directory as the executable. Is it running fine on your PC?

**Comment by gallorob** [comment]
I was trying different things to load the files in the current directory only in specific parts of the application, so it's possible I missed that one.

It should be fixed now, and I've also updated the tiles maker script. Please try again.

**Comment by martinpoliak-goodai** [comment]
Thanks, both the "tileset" and "common_atoms.json" problems are fixed. The AI Spaceship Generator does not run yet though; this time it is unable to locate the hlrules_sm file that sits next to it.

**Comment by gallorob** [comment]
Updated, should be fixed.

**Comment by martinpoliak-goodai** [comment]
Thanks Roberto! I'm thinking that it would be a big help to anyone who'd like to experiment with their own tiles if there were a few sample tiles ready - do you have any tiles that might be included as examples and distributed along with the app?

**Comment by gallorob** [comment]
Sure, I've uploaded a couple of example tiles (corridor with cargo blocks, and thrusters tile).

**Comment by martinpoliak-goodai** [comment]
I am testing the app and it runs fine now (●'◡'●)👍I was able to evolve, recolor & download a spaceship of my choice. I uploaded the release now.

**Comment by martinpoliak-goodai** [comment]
Great, I'll update the release.. and done! I think you can close the issue now.

**Comment by gallorob** [comment]
Awesome, thank you 😄
