### ISSUE TITLE
Can't run the app after building from source

### ISSUE THREAD

**Issue by BrutalMcLegend** [GoodAI/space-engineers-ai-spaceship-generator#23]
**RESOLVED:** To Fix: use scipy version 1.9.2

**Issue type:** BUG? Error on my end?

**Severity:** High (Application Breaking for me)

**Describe the issue**
I can build the source with the `build_main_webapp.py` file, however trying to run the .exe or (directly run the source from the `main_webapp_launcher.py)` will result in the error below.

**To Reproduce**
1. open terminal on the project files location
2. build the project with "`py build_main_webapp.py`"
3. run the resulting .exe in the `dist` folder (or moving it to the main application if it errors for any other reason)
4. Error: 
```
Traceback (most recent call last):
  File "C:\Users\<username>\source\repos\GoodAI's SE-AI_Spaceship_Generator\main_webapp_launcher.py", line 18, in <module>
    from pcgsepy.evo.fitness import (Fitness, box_filling_fitness, func_blocks_fitness, mame_fitness, mami_fitness)
  File "C:\Users\<username>\source\repos\GoodAI's SE-AI_Spaceship_Generator\pcgsepy\evo\fitness.py", line 22, in <module>
    futo_max = float(np.max(futo_es.evaluate(x)))
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\_kde.py", line 270, in evaluate
    points.T, self.cho_cov, output_dtype)
AttributeError: 'gaussian_kde' object has no attribute 'cho_cov'
```

**Expected behavior**
Expected the Application to run.

**Log file**
No log file output as application did not launch.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python Version: 3.9.13 I have now also tried Python Version 3.10.7
 - Browser: Chrome
 - exe's:
     file name: AI Spaceship Generator (no Pytorch)_20230307.exe
     file name: AI Spaceship Generator (with Pytorch)_20230307.exe

*Additional Bits*
I have tried building (without any modifications) both the main branch, and the source of the latest stable release (v1.0.5) to no avail.
TilesMaker.exe builds and runs perfectly fine for port tiles into the llrules and hlrules files.

**NOTE**
Just looking for help on resolving this issue, any help from anyone is appreciated.

**Comment by martinpoliak-goodai** [comment]
What's your version of scipy? I was building the sources with scipy=1.9.2 and on Python 3.10; the error that you got (attribute cho_cov) should not occur on scipy 1.9.2 .
You can also verify quicker if the app works or not by running `python main_webapp_launcher.py` - if it works this way, the built executable should work too

**Comment by BrutalMcLegend** [comment]
> 

Currently running on Python 3.10.7, with Scipy 1.10.1 the error is still there, and I've been into the scipy/_kde file and confirmed, the attribute is indeed there, should I try downgrading Scipy?

also: it's the same error whether I use the `python main_webapp_launcher.py` or the .exe as mentioned above in the report

**Comment by BrutalMcLegend** [comment]
Ahh, I tried my suggestion above (only took a few seconds), downgraded Scipy to 1.9.2 from 1.10.1 and reinstalled Scikit-learn (as it uninstalled it) and that's fixed the issue, and it now builds and runs as expected.

Many thanks for pointing me in the right direction @martinpoliak-goodai
