### ISSUE TITLE
Was this even tested?

### ISSUE THREAD

**Issue by WhtieTigerOfTheNorth** [GoodAI/space-engineers-ai-spaceship-generator#9]
I swear Keen never tests anything.

For starters, the form we need to submit cannot accept JSONs despite them asking for JSON files.

Secondly, some ships won't even evolve past the first generation.

Thirdly, the render window stops working if you are in another tab for long enough.

Thirdly, generation takes FOREVER even on an i9 10940X and two 2080 Tis. 

Marek, resign already. You're alienating your community and ruining a game we love by giving us ZERO significant updates in the last 5 years.

[log_20221110173142.log](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/files/9985631/log_20221110173142.log)

[log_20221110184258.log](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/files/9985623/log_20221110184258.log)

**Comment by WhtieTigerOfTheNorth** [comment]
You could probably recompile it in Python for Linux and get the same if not worse performance, lol. I have a decently powerful computer...and they are expecting the fanbase to go through 4-6 iterations per generation? 

Keen, 90% of the userbase is running like, a 1060 6GB. Holy fuck.

**Comment by Nova1545** [comment]
*Switching to windows fixes it

And yeah, I bet you there are a bunch that are much like yourself hardware wise, but as for myself I have a 1050Ti 4Gb and a i5-9600K, so I fit more in the 90% part

**Comment by WhtieTigerOfTheNorth** [comment]
I mean the 1050 Ti isn't a bad card. The game runs well on low end hardware if you turn settings down.

But the process here was not considered for most users. This is what happens when there is 0 QA/Testing. I can't believe that someone actually published this thinking "yes let's let users sit here for multiple hours for a single test run".

Either Keen's QA is dogshit or they didn't QA it at all.

**Comment by pogue-mahoney** [comment]
Unaffiliated developer here.
This repo is a fork of the actual project by [Araya Research](https://github.com/arayabrain), _not_ Keen.  The project was supported by a Good AI grant.  Good AI is technically _also_ not Keen.  This project cannot be conceived to be in competition for resources with any development priority for Space Engineers. It is research software, by a small group of people demonstrating some big ideas.
If it isn't already obvious, I'll say it outright. Your license for Space Engineers in no way entitles you to have any expectation whatsoever regarding the state of this project.  Even if it did, this "issue", is 1% information and 99% vitriol.  Do the creative world a favor, delete the misspelled GitHub account you made purely to post this drek, and stick to consumption.  Alternatively, do better.

**Comment by WhtieTigerOfTheNorth** [comment]
Get off your high horse, asshole. So what I made a typo. Maybe if your faggot ass had actually tested the software before releasing it this wouldn't be an issue.

Fucking idiot.

**Comment by WhtieTigerOfTheNorth** [comment]
Futhermore, if you got a whole ass GRANT to make this, no wonder it sucks, you pocketed 90% of the money and the remaining 10% went to development of whatever the fuck this half assed program is. 

This definitely wasn't QA tested before release, given the fact that the program runs as a server with a BROWSER AS THE RENDER WINDOW.

It's Python, you could have used OpenGL or Vulkan within the program itself.

In fact if a browser wasn't used, the program could operate 65% more efficiently.

99% high, 1% horse. Kite down, loser.

**Comment by Nova1545** [comment]
@pogue-mahoney Has a very good point, it isn't keen, they are just using it because it was designed to AI generate ships for their game Space Engineers. Though I think Keen did kinda overlook the how long it takes to run on most peoples hardware, not everyone has highend stuff, but as for the general running of it, it runs fine (Just not via WINE)

@WhtieTigerOfTheNorth 
The AI part runs in the python executable, the browser is simply a way of displaying the generated model, (Probably using WebGL, something similar to OpenGL but for web) and providing settings. As for the python part using OpenGL or Vulkan, these would be wrong for the use case of AI computation, OpenCL or CUDA would be (From my understanding) used for the computation as they provide the GPU accleration needed.

**Comment by WhtieTigerOfTheNorth** [comment]
Another issue is that pogue baloney here specializes in C++, not Python so he clearly doesn't understand the issues with the program. 

webGL is notoriously slower than opengl as well, another huge issue with the program.

Everything about this project screams rushed and half-assed.

**Comment by Vodest** [comment]
> Another issue is that pogue baloney here specializes in C++, not Python so he clearly doesn't understand the issues with the program.
> 
> webGL is notoriously slower than opengl as well, another huge issue with the program.
> 
> Everything about this project screams rushed and half-assed.

If you have anything to contribute to GitHub with your recently created account, then feel free to do so.
This is not a Forum board, go complain about the development of this project somewhere else and do not clog up the issues tab with your half-assed whining.

Fork, make your own version and prove your points if you'd like.

**Comment by WhtieTigerOfTheNorth** [comment]
It's not half-assed you're just mad that I'm right

**Comment by martinpoliak-goodai** [comment]
Dear @WhtieTigerOfTheNorth , I would kindly ask you to refrain from using offensive language here. This is an issues section where you are supposed to report issues you found with the program/code. There is no reason not to act kindly to each other here, we're all human beings. If you keep using offensive language, I will block you from this repository. Please consider this as the only and final warning.

As mentioned by others, this is a result of a research project, whose primary outcomes are algorithms for improved evolutionary search and for interactive user+machine evolution. Another outcome is this application which allows you to generate new spaceships for Space Engineers using these algorithms. The application has received a lot of attention from the researchers who developed the method, but it is to be expected, despite a QA round, that some issues may remain. It is for this reason we have the Issues section and invite everyone to submit their issues. 

If you would like to see the issues you mention in your original post resolved, please file separate Issues for each problem you listed, along with details that the Issue template invites you to specify (your system spec, browser, any log files collected etc.)

**Comment by WhtieTigerOfTheNorth** [comment]
You could also, you know, take the feedback instead of acting like you have been. This entire project is a joke and I suggest you also remove your clown makeup and big red nose before responding here again, because honestly I'm laughing at everyone who is defending this sorry excuse of a "Research project". How this ever was approved for a grant is way beyond my understanding.

I can take you out without profanity, but I prefer to be direct. You can also give me your external IP address and home address and we can sort this out face to face if you prefer - that way you know I'm serious about my words, instead of acting like a complete and utter buffoon on the Internet.

**Comment by martinpoliak-goodai** [comment]
Please create separate Issues if you want any of the points you described in your original post to receive further attention.

**Comment by WhtieTigerOfTheNorth** [comment]
Ah yes, make me do more of YOUR work for you. Fuck, you're dense. As if asking the entire SE fanbase to run this shit wasn't enough, now you're begging for more.
